spring:
  application:
    name: notification-mcsv

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  config:
    import:
      - ${SECRET_APP_DEV_PATH}
      - ${SECRET_NOTIFICATION_SERVICE_DEV_PATH}

server:
  port: ${NOTIFICATION_SERVICE_PORT:8085}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized

aws:
  region: us-east-1
  dynamodb:
    endpoint: ""