server:
  port: ${GATEWAY_SERVICE_PORT:8080}

spring:
  application:
    name: api-gateway

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  config:
    import:
      - ${SECRET_APP_PROD_PATH}
      - ${SECRET_API_GATEWAY_PROD_PATH}

  cloud:
    gateway:
      routes:
        # Auth service
        - id: auth-service
          uri: ${USER_SERVICE_URI:http://localhost:8081}
          predicates:
            - Path=/api/auth/**

        # User service
        - id: user-service
          uri: ${USER_SERVICE_URI:http://localhost:8081}
          predicates:
            - Path=/api/users/**

        # Inventory service
        - id: inventory-service
          uri: ${INVENTORY_SERVICE_URI:http://localhost:8082}
          predicates:
            - Path=/api/inventory/**

        # Cart service
        - id: cart-service
          uri: ${CART_SERVICE_URI:http://localhost:8083}
          predicates:
            - Path=/api/cart/**

        # Order service
        - id: order-service
          uri: ${ORDER_SERVICE_URI:http://localhost:8084}
          predicates:
            - Path=/api/orders/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized
