spring:
  application:
    name: cart-mcsv

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  config:
    import:
      - ${SECRET_APP_DEV_PATH}
      - ${SECRET_CART_SERVICE_DEV_PATH}

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

user:
  service:
    url: ${USER_SERVICE_URI:http://localhost:8081}

inventory:
  service:
    url: ${INVENTORY_SERVICE_URI:http://localhost:8082}

server:
  port: ${CART_SERVICE_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized